import React from 'react'
import Card from '../components/Card'
import nagaguard from '../assets/nagaguard.png'
import spacetro from '../assets/spacetro.png'

const Projects = () => {
  return (
    <div className="flex flex-col items-center gap-8 p-8"> 
      <Card imageSrc={"https://c4.rbxcdn.com/7d886a6de2bf7247bd64dee0df2d0756"} title={"AIMSTARS"} skills={[{ text: "Lua" }, { text: "Roblox Studio" }, { text: "Git" }]} description={"In 2020, I developed AIMSTARS, a first-person shooter aim training game on Roblox, which became my most successful project with over 8.9 million plays, 15,000 monthly active users, and $30,000 in revenue. I coded the game in Lua, handling all aspects of production, including 3D modeling and UI design. Key features included sophisticated bots with human-like movement patterns, a global leaderboard system, and a multiplayer mode that boosted engagement by 40%. I also created in-game products that contributed significantly to revenue and actively marketed the game through trailers and ads. This multi-year project honed my programming skills and deepened my understanding of game development, marketing, and user engagement."} />
      <Card imageSrc={nagaguard} title={"NagaGuard"} skills={[{ text: "React" }, { text: "Flask" }, { text: "MySQL" }, { text: "Bootstrap" }, { text: "JavaScript" }, { text: "Python" }]} description={`My team won <strong>Best Startup</strong> at BearHack at <strong>University of California, Riverside</strong>. <strong>Problem:</strong> Local clinics and hospitals spend almost 50% of management funds on manually coding patient data. This process takes several hours daily. Since all clinics and hospitals use the same coding system, we found that Google's <strong>Gemini AI</strong> was familiar with this system and could encode medical reports with 90% accuracy. We built NagaGuard, an AI web app that uses Gemini to input pages of medical reports and encode them in SECONDS! Patients could then review their appointment records instantly.`} />
      <Card imageSrc={spacetro} title={"SpaceTro"} skills={[{ text: "React" }, { text: "Flask" }, { text: "PostgresSQL" }, { text: "Supabase" }, { text: "TailwindCSS" }, { text: "GeminiAI" }]} description={"At a 24-hour hackathon at UC Irvine, I developed Spacetro, an educational full-stack web app designed to inspire people to explore astronomy, particularly young women. I fine-tuned SQL queries to minimize latency, achieving response times under 200ms for data retrieval. I integrated the Gemini API with custom prompt engineering to generate educational articles and quizzes, enhancing the learning experience with interactive content. Additionally, I implemented a real-time leaderboard using Supabase to rank users based on quiz scores, fostering a competitive and engaging environment. I also set up RESTful API endpoints to handle user authentication, profile data storage, and quiz scoring."} />
      <Card imageSrc={"https://c7.rbxcdn.com/3efa2f7703d668fac6e0b614552912d0"} title={"Guess the Build"} skills={[{ text: "Lua" }, { text: "Roblox Studio" }, { text: "Git" }]} description={"I developed a multiplayer guessing game on Roblox, achieving over 150,000 plays worldwide, where players guess items constructed by an assigned builder. Utilizing Roblox Raycasting, I implemented a dynamic block-building system for precise and interactive gameplay. To handle player data and leaderboards, I used ProfileService, ensuring secure and reliable data storage. The game features an in-game shop system managed through MarketplaceService, contributing to a revenue of $3,000. Additionally, I enhanced player engagement by incorporating daily rewards and a feedback system connected via Discord webhooks, allowing direct player communication and continual game improvement based on user input."} />
    </div>
  )
}

export default Projects
